server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eurekad


spring:
  application:
    name: lijo-apigateway-service
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
              allowedOrigins: 'http://localhost:3000'
              allow-credentials: true
              allowedHeaders: '*'
              allowedMethods:
                - PUT
                - GET
                - POST
                - DELETE
                - OPTIONS
#      default-filters:
#        - name: GlobalFilter
#          args:
#            baseMessage: Spring Cloud Gateway Global Filter
#            preLogger: true
#            postLogger: true
      routes:
        #        - id : user-service
        #          uri : lb://USER-SERVICE
        #          predicates :
        #            - Path=/user-service/**
#        - id: user-service
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/user-service/login
#            - Method=POST
#          filters:
#            - RemoveRequestHeader=Cookie # ?? ??? ???? Header ?? ?????? ?? ?? ??? ??? ????.
#            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
#            #/user-service/(?<segment>.*)? ??? ??? ???? /$\{segment} ? ??? ????? ???.
#        - id: user-service
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/user-service/users
#            - Method=POST
#          filters:
#            - RemoveRequestHeader=Cookie # ?? ??? ???? Header ?? ?????? ?? ?? ??? ??? ????.
#            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
#            #/user-service/(?<segment>.*)? ??? ??? ???? /$\{segment} ? ??? ????? ???.
#        - id: user-service
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/user-service/**
#            - Method=GET
#          filters:
#            - RemoveRequestHeader=Cookie # ?? ??? ???? Header ?? ?????? ?? ?? ??? ??? ????.
#            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
#            #/user-service/(?<segment>.*)? ??? ??? ???? /$\{segment} ? ??? ????? ???.
#            - AuthorizationHeaderFilter # ????? ???(login ????) ??? ?? ??? ???? ??? ?? ??.
#        - id : user-service
#          uri : lb://USER-SERVICE
#          predicates :
#            - Path=/user-service/actuator/**
#            - Method=GET,POST
#          filters :
#            - RemoveRequestHeader=Cookie # ?? ??? ???? Header ?? ?????? ?? ?? ??? ??? ????.
#            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: userEvaluation
          uri: lb://USEREVALUATION
          predicates :
            - Path=/userEvaluation/**

        - id: user
          uri: lb://USER
          predicates:
            - Path=/user/**

        - id: socialRoom
          uri: lb://SOCIALROOM
          predicates:
            - Path=/socialRoom/**

#        - id : comments
#          uri : lb://COMMENTS
#          predicates :
#            - Path=/comments/**
#        - id : order-service
#          uri : lb://ORDER-SERVICE
#          predicates :
#            - Path=/order-service/**



#?? custom?? token? ???? ?? ????? ??? ??.
#token:
#  expiration_time: 86400000
#  secret: user_token

#management :
#  endpoints :
#    web :
#      exposure :
#        include : refresh, health, beans, httptrace, busrefresh

